// File generated by FlutterFire CLI.
// This file is a placeholder for the real Firebase configuration
// In a real app, you would generate this file using the FlutterFire CLI

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class FirebaseOptions {
  // ... constructor and other code would be here in a real implementation

  // Mock implementation for demo purposes
  static FirebaseOptions get currentPlatform => const FirebaseOptions(
        apiKey: 'demo-api-key',
        appId: 'demo-app-id',
        messagingSenderId: 'demo-messaging-sender-id',
        projectId: 'demo-project-id',
      );

  const FirebaseOptions({
    required this.apiKey,
    required this.appId,
    required this.messagingSenderId,
    required this.projectId,
    this.authDomain,
    this.databaseURL,
    this.storageBucket,
    this.measurementId,
  });

  final String apiKey;
  final String appId;
  final String? authDomain;
  final String? databaseURL;
  final String messagingSenderId;
  final String projectId;
  final String? storageBucket;
  final String? measurementId;
}