name: Build and Push APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK (verbose)
        run: flutter build apk --release -v

      - name: Check APK exists
        run: |
          if [ -f build/app/outputs/flutter-apk/app-release.apk ]; then
            echo "✅ APK exists"
          else
            echo "❌ APK NOT FOUND"
            ls build/app/outputs/flutter-apk/
            exit 1
          fi

      - name: Push APK to build-artifacts branch
        run: |
          mkdir -p apk-output
          cp build/app/outputs/flutter-apk/app-release.apk apk-output/app-release.apk
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch
          git checkout -B build-artifacts
          git add apk-output/app-release.apk
          git commit -m "Upload built APK"
          git push -f origin build-artifacts
